In [2]:
import pandas as pd
data = { "Name": ["Ravi", "Anu", "Kiran"],
    "Age": [20, 21, 19],
    "City": ["Mysore", "Bengaluru", "Hassan"]}
df = pd.DataFrame(data)
df

    Name  Age       City
0   Ravi   20     Mysore
1    Anu   21  Bengaluru
2  Kiran   19     Hassan

In [3]:
print(type(df))

<class 'pandas.DataFrame'>

In [4]:
df.iloc[0]

Name      Ravi
Age         20
City    Mysore
Name: 0, dtype: object

In [5]:
df.loc[0]

Name      Ravi
Age         20
City    Mysore
Name: 0, dtype: object

In [12]:

df = pd.DataFrame({
    "Name": ["Ravi", "Anu", "Kiran"],
    "Age": [20, 21, 19]
}, index=["0", "1", "2"])
df.loc["1"]

Name    Anu
Age      21
Name: 1, dtype: object

In [13]:
import pandas as pd
df = pd.read_csv("train.csv")
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500

In [14]:
df.shape

(891, 10)

In [15]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name               str
Sex                str
Age            float64
SibSp            int64
Parch            int64
Ticket             str
Fare           float64
dtype: object

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 10 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    str
 4   Sex          891 non-null    str
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    str
 9   Fare         891 non-null    float64
dtypes: float64(2), int64(5), str(3)
memory usage: 103.2 KB

In [17]:
df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [19]:
df.isnull()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
886,False,False,False,False,False,False,False,False,False,False
887,False,False,False,False,False,False,False,False,False,False
888,False,False,False,False,False,True,False,False,False,False
889,False,False,False,False,False,False,False,False,False,False
890,False,False,False,False,False,False,False,False,False,False

In [20]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
dtype: int64

In [23]:
df["Sex"].value_counts()

Sex
male      577
female    314
Name: count, dtype: int64

In [24]:
df["Pclass"].value_counts()

Pclass
3    491
1    216
2    184
Name: count, dtype: int64

In [27]:
df.groupby("Sex")["Survived"].count()

Sex
female    314
male      577
Name: Survived, dtype: int64

In [28]:
df.groupby("Sex")["Survived"].mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

In [29]:
df.groupby("Sex")["Survived"].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [31]:
df.groupby("Sex")["Survived"].count()

Sex
female    314
male      577
Name: Survived, dtype: int64

In [32]:
df.groupby("Pclass")["Survived"].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [35]:
df.groupby("Survived")["Age"].sum()

Survived
0    12985.50
1     8219.67
Name: Age, dtype: float64

In [34]:
df.groupby("Survived")["Age"].mean()

Survived
0    30.626179
1    28.343690
Name: Age, dtype: float64

df.groupby("Survived")["Age"].max()

In [37]:
df.groupby("Pclass")["Survived"].idxmax()

Pclass
1    1
2    9
3    2
Name: Survived, dtype: int64

In [39]:
df.groupby("Pclass")["Survived"].mean().idxmax()

np.int64(1)

# Titanic Dataset — Pandas EDA

This notebook loads and explores the Titanic dataset using Pandas.
I examined the dataset structure, data types, missing values, statistics, and categorical distributions.
I also answered 10 Titanic questions using Pandas operations such as value_counts(), groupby(), sum(), mean(), and max().