# Day 5 — Pandas Cleaning & Transforming

## Part 1 — Titanic Dataset
- Handle missing values
- Encode categorical data
- Feature engineering

## Part 2 — Housing Dataset
- Descriptive statistics
- Correlation analysis
- Top 5 features correlated with price

In [3]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Pavan", "Rahul", "Anu"],
    "Age": [20, None, 21]
})
print(df)

    Name   Age
0  Pavan  20.0
1  Rahul   NaN
2    Anu  21.0

In [2]:
df.dropna()

    Name   Age
0  Pavan  20.0
2    Anu  21.0

In [4]:
df["Age"].fillna(20)

0    20.0
1    20.0
2    21.0
Name: Age, dtype: float64

In [6]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [9]:
import pandas as pd

students = pd.DataFrame({
    "ID": [1, 2, 3],
    "Name": ["Pavan", "Rahul", "Anu"]
})

marks = pd.DataFrame({
    "ID": [1, 2, 3],
    "Marks": [85, 92, 78]
})

result = pd.merge(students, marks, on="ID")

print(result)

   ID   Name  Marks
0   1  Pavan     85
1   2  Rahul     92
2   3    Anu     78

In [13]:
df.drop("Name", axis=1)

    Age
0  20.0
1  20.5
2  21.0

In [14]:
import pandas as pd

df = pd.read_csv("train.csv")

In [16]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [17]:
df["Age"].isnull().sum()

np.int64(0)

In [19]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare'],
      dtype='str')

In [20]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500

In [21]:
df["Age"].isnull().sum()

np.int64(0)

In [22]:
df["Sex"].unique()

<ArrowStringArray>
['male', 'female']
Length: 2, dtype: str

In [23]:
df["Sex"] = df["Sex"].map({
    "male": 1,
    "female": 0
})

In [24]:
df["Sex"].unique()

array([1, 0])

In [25]:
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1

In [26]:
df[["SibSp", "Parch", "FamilySize"]].head()

   SibSp  Parch  FamilySize
0      1      0           2
1      1      0           2
2      0      0           1
3      1      0           2
4      0      0           1

In [27]:
df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
FamilySize     0
dtype: int64

In [30]:
housing_df = pd.read_csv("Housing.csv")

In [31]:
housing_df.describe()

,price,area,bedrooms,bathrooms,stories,parking
count,5.450000e+02,545.000000,545.000000,545.000000,545.000000,545.000000
mean,4.766729e+06,5150.541284,2.965138,1.286239,1.805505,0.693578
std,1.870440e+06,2170.141023,0.738064,0.502470,0.867492,0.861586
min,1.750000e+06,1650.000000,1.000000,1.000000,1.000000,0.000000
25%,3.430000e+06,3600.000000,2.000000,1.000000,1.000000,0.000000
50%,4.340000e+06,4600.000000,3.000000,1.000000,2.000000,0.000000
75%,5.740000e+06,6360.000000,3.000000,2.000000,2.000000,1.000000
max,1.330000e+07,16200.000000,6.000000,4.000000,4.000000,3.000000

In [32]:
housing_df.corr(numeric_only=True)["price"].sort_values(ascending=False)

price        1.000000
area         0.535997
bathrooms    0.517545
stories      0.420712
parking      0.384394
bedrooms     0.366494
Name: price, dtype: float64

In [33]:
housing_df.shape

(545, 13)

In [35]:
housing_df.head()

,price,area,bedrooms,bathrooms,stories,mainroad,guestroom,basement,hotwaterheating,airconditioning,parking,prefarea,furnishingstatus
0,13300000,7420,4,2,3,yes,no,no,no,yes,2,yes,furnished
1,12250000,8960,4,4,4,yes,no,no,no,yes,3,no,furnished
2,12250000,9960,3,2,2,yes,no,yes,no,no,2,yes,semi-furnished
3,12215000,7500,4,2,2,yes,no,yes,no,yes,3,yes,furnished
4,11410000,7420,4,1,2,yes,yes,yes,no,yes,2,no,furnished

In [36]:
housing_df.isnull().sum()

price               0
area                0
bedrooms            0
bathrooms           0
stories             0
mainroad            0
guestroom           0
basement            0
hotwaterheating     0
airconditioning     0
parking             0
prefarea            0
furnishingstatus    0
dtype: int64

In [39]:
small = housing_df[["price", "area", "bedrooms"]].head().copy()

In [40]:
small.map(lambda x: x * 2)

      price   area  bedrooms
0  26600000  14840         8
1  24500000  17920         8
2  24500000  19920         6
3  24430000  15000         8
4  22820000  14840         8